name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  REPO_NAME: hello
  AWS_USE_FIPS_ENDPOINT: "true"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS CLI to Use FIPS Endpoint
        run: |
          aws configure set ecr.endpoint_url https://ecr-fips.${{ env.AWS_REGION }}.amazonaws.com
          aws configure set default.region $AWS_REGION

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region $AWS_REGION --endpoint-url https://ecr-fips.$AWS_REGION.amazonaws.com | docker login --username AWS --password-stdin https://ecr-fips.$AWS_REGION.amazonaws.com
          

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_FIPS_REGISTRY: ecr-fips.${{ env.AWS_REGION }}.amazonaws.com
          IMAGE_TAG: ${{ github.sha }}
        run: |
          
          # Build the Docker image
          docker build -t $ECR_FIPS_REGISTRY/$REPO_NAME:$IMAGE_TAG .
          
          # Push using FIPS endpoint
          docker push $ECR_FIPS_REGISTRY/$REPO_NAME:$IMAGE_TAG
          
          echo "image=$ECR_FIPS_REGISTRY/$REPO_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

    
