name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  REPO_NAME: hello
  AWS_USE_FIPS_ENDPOINT: "true"
  AWS_ACCOUNT_ID: "025482195245"
  ECR_FIPS_ENDPOINT: "https://ecr-fips.us-east-1.amazonaws.com"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS CLI to Use FIPS Endpoint
        run: |
          aws configure set ecr.endpoint_url https://ecr-fips.${{ env.AWS_REGION }}.amazonaws.com
          aws configure set default.region $AWS_REGION

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          # Set the registry URL
          ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr-fips.${AWS_REGION}.amazonaws.com"
          echo "registry=${ECR_REGISTRY}" >> $GITHUB_OUTPUT
          
          # Login to ECR
          aws ecr get-login-password \
            --region ${{ env.AWS_REGION }} \
            --endpoint-url https://ecr-fips.us-east-1.amazonaws.com | \
          docker login \
            --username AWS \
            --password-stdin ${ECR_REGISTRY}
          

      - name: Build, tag, and push image to Amazon ECR
        run: |
          # Set the full image name
          IMAGE_URI="${{ env.AWS_ACCOUNT_ID }}.dkr.ecr-fips.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${{ github.sha }}"
          
          # Build the Docker image
          docker build -t ${IMAGE_URI} .
          
          # Push using FIPS endpoint
          docker push ${IMAGE_URI}
          
          # Save the image URI for later use
          echo "image=${IMAGE_URI}" >> $GITHUB_OUTPUT

      - name: Verify Push
        run: |
          aws ecr describe-images \
            --repository-name ${{ env.REPO_NAME }} \
            --image-ids imageTag=${{ github.sha }} \
            --endpoint-url https://ecr-fips.us-east-1.amazonaws.com 

    
